# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-31 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20190131_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Client'},
        ),
    ]
